[tool.poetry.dependencies]
aiohttp = "==3.8.4"
aiohttp-cors = "==0.7.0"
aiosignal = "==1.3.1"
async-timeout = "==4.0.2"
attrs = "==23.1.0"
blessed = "==1.20.0"
boto3 = "==1.26.133"
botocore = "==1.29.133"
cachetools = "==5.3.0"
certifi = "==2023.5.7"
charset-normalizer = "==3.1.0"
click = "==8.1.3"
colorama = "==0.4.6"
colorful = "==0.5.5"
distlib = "==0.3.6"
filelock = "==3.12.0"
frozenlist = "==1.3.3"
fsspec = "==2023.4.0"
google-api-core = "==2.11.0"
google-auth = "==2.18.0"
googleapis-common-protos = "==1.59.0"
gpustat = "==1.1"
grpcio = "==1.51.3"
idna = "==3.4"
jmespath = "==1.0.1"
jsonschema = "==4.17.3"
msgpack = "==1.0.5"
multidict = "==6.0.4"
numpy = "==1.24.3"
nvidia-ml-py = "==11.525.112"
opencensus = "==0.11.2"
opencensus-context = "==0.1.3"
packaging = "==23.1"
pandas = "==1.5.3"
pip = "==23.1.2"
platformdirs = "==3.5.1"
prometheus-client = "==0.16.0"
protobuf = "==4.23.0"
psutil = "==5.9.5"
py-spy = "==0.3.14"
PyAmazonCACerts = "==1.0"
pyarrow = "==11.0.0"
pyasn1 = "==0.5.0"
pyasn1-modules = "==0.3.0"
pydantic = "==1.10.7"
pyrsistent = "==0.19.3"
python-dateutil = "==2.8.2"
pytz = "==2023.3"
PyYAML = "==6.0"
ray = "==2.4.0"
requests = "==2.31.0"
rsa = "==4.9"
s3transfer = "==0.6.1"
setproctitle = "==1.2.2"
setuptools = "==67.7.2"
setuptools-scm = "==7.1.0"
six = "==1.16.0"
smart-open = "==6.2.0"
tomli = "==2.0.1"
typing_extensions = "==4.5.0"
urllib3 = "==1.26.15"
virtualenv = "==20.21.0"
wcwidth = "==0.2.6"
yarl = "==1.9.2"
